// AUTH TYPES
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_LOGOUT_USER_FAIL = 'AUTH_LOGOUT_USER_FAIL';
export const AUTH_LOGOUT_USER_SUCCESS = 'AUTH_LOGOUT_USER_SUCCESS';
export const AUTH_USER_LOGGED_ONCE = 'AUTH_USER_LOGGED_ONCE';
export const AUTH_USER_IS_LOGGED_ONCE_SUCCESS = 'AUTH_USER_IS_LOGGED_ONCE_SUCCESS';
export const AUTH_USER_IS_NOT_LOGGED_ONCE = 'AUTH_USER_IS_NOT_LOGGED_ONCE';
export const AUTH_IS_USER_LOGGED = 'AUTH_IS_USER_LOGGED';
export const AUTH_USER_IS_LOGGED = 'AUTH_USER_IS_LOGGED';
export const AUTH_USER_IS_NOT_LOGGED = 'AUTH_USER_IS_NOT_LOGGED';
// PROFILE TYPES
export const PROFILE_FETCH = 'PROFILE_FETCH';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'